# see https://github.com/karlicoss/pymplate for up-to-date reference

name: CI
on:
  push:
    branches: '*'
    tags: 'v[0-9]+.*' # only trigger on 'release' tags for PyPi
    # Ideally I would put this in the pypi job... but github syntax doesn't allow for regexes there :shrug:

  # Needed to trigger on others' PRs.
  # Note that people who fork it need to go to "Actions" tab on their fork and click "I understand my workflows, go ahead and enable them".
  pull_request:

  # Needed to trigger workflows manually.
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

  schedule:
    - cron: '31 18 * * 5'  # run every Friday


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12', '3.13', '3.14']
        exclude: [
            # windows runners are pretty scarce, so let's only run lowest and highest python version
            {platform: windows-latest, python-version: '3.13'},

            # same, macos is a bit too slow and ubuntu covers python quirks well
            {platform: macos-latest  , python-version: '3.13'},
        ]

    runs-on: ${{ matrix.platform }}

    # useful for 'optional' pipelines
    # continue-on-error: ${{ matrix.platform == 'windows-latest' }}

    steps:
    # ugh https://github.com/actions/toolkit/blob/main/docs/commands.md#path-manipulation
    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 0  # nicer to have all git history when debugging/for tests

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
      
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false  # we don't have lock files, so can't use them as cache key

    - uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    # explicit bash command is necessary for Windows CI runner, otherwise it thinks it's cmd...
    - run: bash .ci/run

  ###
  # PyPI publishing disabled for personal fork - not needed since we won't be publishing packages
  # To re-enable, rename this job back to 'pypi' and set up CODECOV_TOKEN secret if desired

  ###
  build_extension:
    env:
      name: 'promnesia'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
        fetch-depth: 0  # nicer to have all git history when debugging/for tests

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: extension/.ci/build --lint # debug version
    - run: extension/.ci/build --lint --release

    # TODO ugh. can't share github actions artifacts publicly...
    # TODO for fuck's sake... why does it end up named as .zip.zip ????
    - uses: actions/upload-artifact@v4
      with:
        name: '${{ env.name }}-chrome-debug-latest.zip'
        path: 'extension/dist/artifacts/chrome/${{ env.name }}_dev_-*.zip'
    - uses: actions/upload-artifact@v4
      with:
        name: '${{ env.name }}-chrome-release-latest.zip'
        path: 'extension/dist/artifacts/chrome/${{ env.name }}-*.zip'
    - uses: actions/upload-artifact@v4
      with:
        name: '${{ env.name }}-firefox-debug-latest.zip'
        path: 'extension/dist/artifacts/firefox/${{ env.name }}_dev_-*.zip'
    - uses: actions/upload-artifact@v4
      with:
        name: '${{ env.name }}-firefox-release-latest.zip'
        path: 'extension/dist/artifacts/firefox/${{ env.name }}-*.zip'

  # split in two pipelines to speedup running
  end2end_tests_chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - run: .ci/end2end/build_and_run.sh -k chrome

  end2end_tests_firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
    - run: .ci/end2end/build_and_run.sh -k firefox

  install_and_run_test:
    # todo use setup-python thing?
    # todo run on macos too?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - run: .ci/github-ci-compat

    - run: |
        python3 -m pip install .
        export PATH=.ci/fake-systemd:$PATH
        tests/install_and_run

